name: emimesh
channels:
  - conda-forge
dependencies:
  - matplotlib
  - pyvista
  - scikit-image
  - meshio
  - dask-image
  - seaborn
  - pyacvd
  - zip
  - pip
  - pip:
    - pytetwild
    - fastremap
    - cloud-volume
    - webknossos
    - connected-components-3d
    - cmocean
    - nbmorph
