name: emimesh
channels:
  - conda-forge
dependencies:
  - matplotlib
  - pyvista
  - scikit-image
  - meshio
  - dask-image
  - seaborn
  - pyacvd
  - pip
  - pip:
      - pytetwild
      - fastremap
      - cloud-volume
      # - webknossos # Needs to unpin it's zipp versioning, ref: https://github.com/scalableminds/webknossos-libs/issues/1421
      - connected-components-3d
      - cmocean
      - nbmorph
      - -e ../..
